# Generated by Django 5.2.7 on 2025-10-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycurrency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
