# Generated by Django 5.2.7 on 2025-10-26 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_countrycurrency_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrycurrency',
            name='exchange_rate',
        ),
    ]
