// @ts-check
import React, { useState, useEffect } from 'react'
import {
  Loader2,
  CheckCircle2,
  AlertCircle,
  ArrowLeft,
  RefreshCw,
  PlugZap,
  Unplug,
  Copy,
  Check,
  Network,
  Eye,
  EyeOff,
  FlaskConical,
  ShieldAlert,
} from 'lucide-react'
import { toast } from 'react-hot-toast'
import { getNetwork, shortAddress } from '../../services/walletNetworks'
import { useWallet } from '../../context/WalletContext'
import { walletAPI } from '../../services/walletApi'
import { canInjectEVM, canInjectSolana } from '../../services/walletList'
import { WALLET_ERRORS, hasInjectedEVM, hasInjectedSolana } from '../../services/walletConnectors'
import WalletIcon from './WalletIcon'
import Button from '../UI/Button'

/**
 * WalletConnectionPanel - the wallet connection screen.
 * Lets the user pick a network (from the wallets' supported chains), initiates a
 * legitimate connection (injected provider / WalletConnect), shows loading,
 * success and failure states, and lets the user disconnect or pick another
 * wallet. Never touches secrets - the wallet itself authorises the connection.
 *
 * A clearly-labelled SIMULATION mode (demo only) is also available: the demo
 * seed phrase is generated by the backend (bip39) and shown once for the user
 * to "save" - the app never accepts a user-typed seed phrase anywhere.
 */
const WalletConnectionPanel = ({ wallet, onBack, onConnected, isModal = true }) => {
  const { connection, connect, disconnect, setConnected } = useWallet()

  const defaultNetworkId = (wallet.networks || []).includes(connection?.network)
    ? connection.network
    : wallet.networks[0]
  const [networkId, setNetworkId] = useState(defaultNetworkId)
  const [connecting, setConnecting] = useState(false)
  const [error, setError] = useState('')
  const [disconnecting, setDisconnecting] = useState(false)
  const [copied, setCopied] = useState(false)

  // Simulation (demo) state
  const [simulateMode, setSimulateMode] = useState(false)
  const [simPhraseWords, setSimPhraseWords] = useState(
    wallet.category === 'Hardware Wallet' ? 24 : 12
  )
  const [simBusy, setSimBusy] = useState(false)
  const [simError, setSimError] = useState('')
  const [simConnection, setSimConnection] = useState(null)
  const [simPhrase, setSimPhrase] = useState('')
  const [showPhrase, setShowPhrase] = useState(false)
  const [phraseCopied, setPhraseCopied] = useState(false)
  const [simConfirmed, setSimConfirmed] = useState(false)

  const network = getNetwork(networkId)
  const alreadyConnected = connection && connection.walletProviderId === wallet.id && connection.network === networkId
  const supportsInjection =
    (canInjectEVM(wallet) && network?.family === 'evm' && hasInjectedEVM()) ||
    (canInjectSolana(wallet) && network?.family === 'solana' && hasInjectedSolana())

  useEffect(() => {
    const next = (wallet.networks || []).includes(connection?.network)
      ? connection.network
      : wallet.networks[0]
    setNetworkId(next)
    setError('')
    setSimulateMode(false)
    setSimError('')
    setSimConnection(null)
    setSimPhrase('')
    setShowPhrase(false)
    setSimConfirmed(false)
    setSimPhraseWords(wallet.category === 'Hardware Wallet' ? 24 : 12)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [wallet.id])

  const handleConnect = async () => {
    if (!network) return
    setError('')
    setConnecting(true)
    try {
      const saved = await connect(wallet, network)
      toast.success(`${wallet.name} connected`)
      onConnected?.(saved)
    } catch (connectError) {
      const rawMessage = connectError?.message || 'Connection failed. Please try again.'
      setError(rawMessage)
      if (connectError?.code === WALLET_ERRORS.USER_REJECTED) {
        // Graceful handling - wallet declined/closed the prompt.
      }
    } finally {
      setConnecting(false)
    }
  }

  const handleDisconnect = async () => {
    if (!connection) return
    setDisconnecting(true)
    try {
      await disconnect()
      toast.success('Wallet disconnected')
      onBack?.()
    } catch (disconnectError) {
      toast.error(disconnectError?.message || 'Failed to disconnect wallet.')
    } finally {
      setDisconnecting(false)
    }
  }

  const copyAddress = async () => {
    if (!connection) return
    try {
      await navigator.clipboard.writeText(connection.walletAddress)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch (e) {
      toast.error('Could not copy address.')
    }
  }

  // Simulation (demo) handlers -------------------------------------------------
  const handleSimulate = async () => {
    if (!network) return
    setSimError('')
    setSimBusy(true)
    try {
      const response = await walletAPI.simulate({
        walletProviderId: wallet.id,
        walletProviderName: wallet.name,
        network: networkId,
        phraseWords: simPhraseWords,
      })
      // The demo phrase is generated server-side and returned exactly once.
      setSimConnection(response.data)
      setSimPhrase(response.simulatedSeedPhrase)
      setShowPhrase(false)
      setSimConfirmed(false)
      setConnected(response.data)
      toast.success(`Simulated ${wallet.name} created`)
    } catch (simErrorObject) {
      setSimError(simErrorObject?.message || 'Failed to create the simulated wallet.')
    } finally {
      setSimBusy(false)
    }
  }

  const copyPhrase = async () => {
    if (!simPhrase) return
    try {
      await navigator.clipboard.writeText(simPhrase)
      setPhraseCopied(true)
      setTimeout(() => setPhraseCopied(false), 1500)
    } catch (e) {
      toast.error('Could not copy the phrase.')
    }
  }

  const header = (
    <div className="relative bg-gradient-to-br from-primary-700 via-primary-800 to-primary-900 px-6 py-6 text-center overflow-hidden">
      <div className="pointer-events-none absolute -top-16 -right-10 w-44 h-44 rounded-full bg-gold/20 blur-3xl" />
      <div className="relative flex flex-col items-center">
        <WalletIcon wallet={wallet} size="lg" showRing />
        <h3 className="text-lg font-heading font-semibold text-white mt-3">Connect {wallet.name}</h3>
        <p className="text-xs text-white/60 mt-1 max-w-xs">
          Approve the connection inside your wallet. Your keys never leave it.
        </p>
      </div>
    </div>
  )

  return (
    <>
      {header}

      <div className="p-6">
      {connecting ? (
        <div className="text-center py-8">
          <Loader2 size={38} className="animate-spin text-gold mx-auto" />
          <h4 className="font-heading font-semibold text-lg text-primary dark:text-cream mt-4">
            Waiting for approval...
          </h4>
          <p className="text-sm text-silver mt-2">
            Open <span className="font-semibold text-primary dark:text-cream">{wallet.name}</span>{' '}
            {supportsInjection ? 'in your browser' : 'and scan the QR code with your phone'} to approve the
            connection on <span className="font-mono">{network?.name}</span>.
          </p>
          <p className="text-xs text-silver/70 mt-4 flex items-center justify-center gap-1.5">
            <PlugZap size={13} className="text-gold" /> This request is safe — no private keys are ever requested.
          </p>
        </div>
      ) : alreadyConnected ? (
        <div className="text-center">
          <div className="w-16 h-16 rounded-full bg-success/15 text-success flex items-center justify-center mx-auto">
            <CheckCircle2 size={30} />
          </div>
          <h4 className="font-heading font-semibold text-lg text-primary dark:text-cream mt-3">Wallet connected</h4>
          <button
            onClick={copyAddress}
            className="mt-3 inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-primary-100 dark:bg-primary-700 text-primary dark:text-cream font-mono text-sm hover:bg-primary-200 dark:hover:bg-primary-600 transition-colors"
          >
            {connection.walletAddress === connection.walletAddress ? shortAddress(connection.walletAddress) : ''}
            {copied ? <Check size={15} className="text-success" /> : <Copy size={15} className="text-silver" />}
          </button>
          <p className="text-xs text-silver mt-1.5 capitalize">{network?.name} · {wallet.name}</p>

          <div className="flex flex-col sm:flex-row gap-2 mt-6">
            <Button variant="ghost" className="flex-1" onClick={handleDisconnect} disabled={disconnecting}>
              {disconnecting ? <Loader2 size={15} className="animate-spin mr-1" /> : <Unplug size={15} className="mr-1" />}
              Disconnect
            </Button>
            <Button variant="ghost" className="flex-1" onClick={onBack}>
              <RefreshCw size={15} className="mr-1" /> Change wallet
            </Button>
            <Button variant="brand" className="flex-1" onClick={() => onConnected?.(connection)}>
              Continue <ArrowLeft size={15} className="ml-1 rotate-180" />
            </Button>
          </div>
        </div>
      ) : simulateMode ? (
        <SimulatedWalletView
          wallet={wallet}
          network={network}
          simPhraseWords={simPhraseWords}
          setSimPhraseWords={setSimPhraseWords}
          simBusy={simBusy}
          simError={simError}
          simPhrase={simPhrase}
          showPhrase={showPhrase}
          setShowPhrase={setShowPhrase}
          phraseCopied={phraseCopied}
          simConfirmed={simConfirmed}
          setSimConfirmed={setSimConfirmed}
          onGenerate={handleSimulate}
          onCopyPhrase={copyPhrase}
          onRegenerate={() => { setSimPhrase(''); setSimConnection(null) }}
          onBackReal={() => setSimulateMode(false)}
          onContinue={() => onConnected?.()}
        />
      ) : (
        <>
          {/* Network selector - only networks this wallet actually supports */}
          <div>
            <label className="block text-sm font-medium text-primary dark:text-cream mb-2 flex items-center gap-2">
              <Network size={15} className="text-gold" /> Network
            </label>
            <select
              value={networkId}
              onChange={(e) => { setNetworkId(e.target.value); setError('') }}
              className="w-full px-4 py-3 bg-primary-100 dark:bg-primary-700 border border-silver/40 dark:border-primary-600 rounded-xl text-sm focus:ring-2 focus:ring-gold focus:border-transparent"
            >
              {(wallet.networks || []).map((nid) => {
                const n = getNetwork(nid)
                return (
                  <option key={nid} value={nid}>
                    {n ? `${n.name} (${n.shortName})` : nid}
                  </option>
                )
              })}
            </select>
            <p className="text-xs text-silver mt-2">
              Only networks supported by {wallet.name} are listed.
            </p>
          </div>

          {error && (
            <div className="mt-4 flex items-start gap-2 bg-danger-light dark:bg-danger/10 border border-danger/30 rounded-xl p-3">
              <AlertCircle size={16} className="text-danger shrink-0 mt-0.5" />
              <p className="text-sm text-danger-dark dark:text-danger-light">{error}</p>
            </div>
          )}

          <div className="mt-5 flex flex-col sm:flex-row gap-2">
            <Button variant="ghost" className="flex-1" onClick={onBack}>
              <ArrowLeft size={15} className="mr-1" /> Change wallet
            </Button>
            <Button variant="brand" className="flex-1" onClick={handleConnect} disabled={!network}>
              <PlugZap size={16} className="mr-1" /> Connect
            </Button>
          </div>

          <p className="text-xs text-silver text-center mt-4">
            Connecting uses the official{' '}
            {supportsInjection
              ? 'injected browser provider (EIP-1193)'
              : 'WalletConnect protocol'}{' '}
            — your recovery phrase or private key is never requested, stored or shared.
          </p>

          {/* Divider + Simulation toggle */}
          <div className="flex items-center gap-3 my-4">
            <div className="flex-1 h-px bg-silver/30 dark:bg-primary-600" />
            <p className="text-xs font-semibold uppercase tracking-wider text-silver">or</p>
            <div className="flex-1 h-px bg-silver/30 dark:bg-primary-600" />
          </div>
          <button
            onClick={() => setSimulateMode(true)}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl border border-dashed border-gold/50 text-gold hover:bg-gold/10 transition-colors text-sm font-semibold"
          >
            <FlaskConical size={16} /> Use simulation (demo)
          </button>
        </>
      )}
      </div>
    </>
  )
}

/**
 * SimulatedWalletView - demo-only "connect a wallet" experience.
 * The demo seed phrase is ALWAYS generated by the backend (bip39) and shown
 * once. There is deliberately NO text input here: the app never accepts a
 * user-typed seed phrase, so a real wallet secret can never be captured.
 */
const SimulatedWalletView = ({
  network,
  simPhraseWords,
  setSimPhraseWords,
  simBusy,
  simError,
  simPhrase,
  showPhrase,
  setShowPhrase,
  phraseCopied,
  simConfirmed,
  setSimConfirmed,
  onGenerate,
  onCopyPhrase,
  onRegenerate,
  onBackReal,
  onContinue,
}) => (
  <div className="space-y-4">
    <div className="flex items-start gap-2 bg-gold/10 border border-gold/30 rounded-xl p-3">
      <FlaskConical size={16} className="text-gold shrink-0 mt-0.5" />
      <div>
        <p className="text-sm font-semibold text-gold">Simulation mode (demo only)</p>
        <p className="text-xs text-silver mt-1 leading-relaxed">
          A fake {simPhraseWords}-word seed phrase will be generated by the app so you can experience the wallet flow.
          Never enter a real wallet seed phrase anywhere in this app.
        </p>
      </div>
    </div>

    {!simPhrase ? (
      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-primary dark:text-cream mb-2">Seed phrase length</label>
          <div className="flex gap-2">
            {[12, 24].map((w) => (
              <button
                key={w}
                onClick={() => setSimPhraseWords(w)}
                className={`flex-1 px-4 py-2.5 rounded-xl text-sm font-semibold border transition-all ${
                  simPhraseWords === w
                    ? 'bg-gold text-white border-gold shadow-lux-gold'
                    : 'bg-white dark:bg-primary-800 text-silver border-silver/30 dark:border-primary-600 hover:text-primary dark:hover:text-cream'
                }`}
              >
                {w} words
              </button>
            ))}
          </div>
        </div>

        {simError && (
          <div className="flex items-start gap-2 bg-danger-light dark:bg-danger/10 border border-danger/30 rounded-xl p-3">
            <AlertCircle size={16} className="text-danger shrink-0 mt-0.5" />
            <p className="text-sm text-danger-dark dark:text-danger-light">{simError}</p>
          </div>
        )}

        <div className="flex flex-col sm:flex-row gap-2">
          <Button variant="ghost" className="flex-1" onClick={onBackReal}>
            <ArrowLeft size={15} className="mr-1" /> Use real wallet
          </Button>
          <Button variant="brand" className="flex-1" onClick={onGenerate} disabled={simBusy || !network}>
            {simBusy ? <Loader2 size={16} className="animate-spin mr-1" /> : <FlaskConical size={16} className="mr-1" />}
            Generate simulated wallet
          </Button>
        </div>
      </div>
    ) : (
      <div className="space-y-4">
        <div className="bg-primary-50 dark:bg-primary-700/60 rounded-2xl p-4 border border-silver/25 dark:border-primary-600">
          <p className="text-xs font-semibold uppercase tracking-wider text-gold mb-2">
            Your simulated {simPhraseWords}-word seed phrase
          </p>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
            {simPhrase.split(' ').map((word, index) => (
              <div key={index} className="bg-white dark:bg-primary-600 rounded-lg px-3 py-2 text-center font-mono border border-silver/30">
                <span className="text-[10px] text-silver mr-1.5">{index + 1}.</span>
                {showPhrase ? word : '••••••'}
              </div>
            ))}
          </div>
          <div className="flex gap-2 mt-3">
            <button
              onClick={() => setShowPhrase(!showPhrase)}
              className="flex-1 inline-flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg bg-primary-100 dark:bg-primary-700 text-xs font-semibold text-primary dark:text-cream hover:bg-primary-200 dark:hover:bg-primary-600 transition-colors"
            >
              {showPhrase ? <EyeOff size={14} /> : <Eye size={14} />} {showPhrase ? 'Hide' : 'Reveal'}
            </button>
            <button
              onClick={onCopyPhrase}
              className="flex-1 inline-flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg bg-primary-100 dark:bg-primary-700 text-xs font-semibold text-primary dark:text-cream hover:bg-primary-200 dark:hover:bg-primary-600 transition-colors"
            >
              {phraseCopied ? <Check size={14} className="text-success" /> : <Copy size={14} />} {phraseCopied ? 'Copied' : 'Copy'}
            </button>
          </div>
        </div>

        <label className="flex items-start gap-3 cursor-pointer select-none">
          <input type="checkbox" checked={simConfirmed} onChange={(e) => setSimConfirmed(e.target.checked)} className="mt-0.5 w-5 h-5 accent-primary-600" />
          <span className="text-sm text-primary dark:text-cream">
            I have saved my simulated seed phrase
            <span className="block text-xs text-silver mt-0.5">This is demo data generated by the app — it is not a real wallet.</span>
          </span>
        </label>

        <div className="flex flex-col sm:flex-row gap-2">
          <Button variant="ghost" className="flex-1" onClick={onRegenerate}>
            <RefreshCw size={15} className="mr-1" /> Regenerate
          </Button>
          <Button variant="brand" className="flex-1" disabled={!simConfirmed} onClick={onContinue}>
            <CheckCircle2 size={16} className="mr-1" /> I've saved it — Continue
          </Button>
        </div>
      </div>
    )}
  </div>
)

export default WalletConnectionPanel